const express = require('express');
const fileController = require('../controllers/fileController');
const explorerController = require('../controllers/explorerController');
const zipController = require('../controllers/zipController');
const terminalController = require('../controllers/terminalController');
const chatController = require('../controllers/chatController');
const statusController = require('../controllers/statusController');
const missionController = require('../controllers/missionController');
const scannerController = require('../controllers/scannerController');
const projectAssistantController = require('../controllers/projectAssistantController');
const storageController = require('../controllers/storageController');
const aiManagerController = require('../controllers/aiManagerController');
const foundationController = require('../controllers/foundationController');
const discoveryEngineController = require('../controllers/discoveryEngineController');
const arbitragePipelineController = require('../controllers/arbitragePipelineController');
const arbitrageEngineController = require('../controllers/arbitrageEngineController');
const homologationController = require('../controllers/homologationController');
const sourceIntelligenceController = require('../controllers/sourceIntelligenceController');
const liveAuditLabController = require('../controllers/liveAuditLabController');

const router = express.Router();

router.get('/status', statusController.status);
router.get('/project/tree', explorerController.workspaceTree);
router.get('/explorer', explorerController.explorePath);
router.post('/explorer/create', explorerController.createNode);
router.post('/explorer/rename', explorerController.renameNode);
router.post('/explorer/delete', explorerController.deleteNode);
router.post('/explorer/paste', explorerController.pasteNode);
router.post('/explorer/duplicate', explorerController.duplicateNode);
router.post('/file/read', fileController.readFile);
router.post('/file/write', fileController.writeFile);
router.post('/zip/create', zipController.createZip);
router.post('/zip/import', zipController.importZip);
router.get('/zip/download', zipController.downloadZip);
router.post('/terminal/exec', terminalController.execute);
router.post('/terminal/cancel', terminalController.cancel);
router.post('/chat/message', chatController.sendMessage);
router.post('/chat/stream', chatController.streamMessage);
router.get('/chat/conversations', chatController.listConversations);
router.post('/chat/conversations', chatController.createConversation);
router.delete('/chat/conversations', chatController.deleteAllConversations);
router.post('/chat/conversations/import', chatController.importConversation);
router.get('/chat/conversations/:id', chatController.loadConversation);
router.patch('/chat/conversations/:id', chatController.renameConversation);
router.delete('/chat/conversations/:id', chatController.deleteConversation);
router.post('/chat/conversations/:id/duplicate', chatController.duplicateConversation);
router.patch('/chat/conversations/:id/pin', chatController.pinConversation);
router.post('/chat/conversations/:id/clear', chatController.clearConversation);
router.post('/chat/conversations/:id/share', chatController.shareConversation);
router.get('/chat/conversations/:id/export', chatController.exportConversation);
router.patch('/chat/conversations/:id/messages/:messageId', chatController.updateMessage);
router.delete('/chat/conversations/:id/messages/:messageId', chatController.deleteMessage);

router.post('/missions', missionController.createMission);
router.get('/missions', missionController.listMissions);
router.get('/missions/:id', missionController.getMission);
router.patch('/missions/:id/status', missionController.updateMissionStatus);
router.patch('/missions/:id', missionController.editMission);
router.delete('/missions/:id', missionController.deleteMission);

router.get('/scanner/scan', scannerController.scan);
router.get('/scanner/state', scannerController.state);
router.post('/scanner/cancel', scannerController.cancel);
router.get('/scanner/tree', scannerController.tree);
router.get('/scanner/summary', scannerController.summary);
router.get('/scanner/index', scannerController.index);

router.get('/assistant/modules', projectAssistantController.listModules);
router.get('/assistant/modules/:id', projectAssistantController.getModule);
router.post('/assistant/modules/:id/update', projectAssistantController.updateModule);
router.post('/assistant/modules/:id/uninstall', projectAssistantController.uninstallModule);
router.patch('/assistant/modules/:id/configuration', projectAssistantController.configureModule);

router.get('/discovery/houses', discoveryEngineController.list);
router.post('/discovery/houses/save-configuration', discoveryEngineController.saveConfiguration);
router.post('/discovery/houses', discoveryEngineController.create);
router.post('/discovery/houses/import', discoveryEngineController.importHouses);
router.get('/discovery/houses/export', discoveryEngineController.exportHouses);
router.patch('/discovery/houses/:id', discoveryEngineController.update);
router.delete('/discovery/houses/:id', discoveryEngineController.remove);
router.patch('/discovery/houses/:id/active', discoveryEngineController.activate);
router.patch('/discovery/houses/:id/block', discoveryEngineController.block);
router.post('/discovery/houses/:id/run', discoveryEngineController.run);
router.get('/discovery/houses/:id/status', discoveryEngineController.status);
router.get('/discovery/houses/:id/profile', discoveryEngineController.exportProfile);
router.post('/discovery/profiles/import', discoveryEngineController.importProfile);
router.get('/pipeline/status', arbitragePipelineController.status);
router.patch('/pipeline/operational-mode', arbitragePipelineController.operationalMode);
router.post('/pipeline/readers/generate', arbitragePipelineController.generateReaders);
router.patch('/pipeline/readers/:id/active', arbitragePipelineController.readerActive);
router.post('/pipeline/readers/:id/run', arbitragePipelineController.readerRun);
router.get('/pipeline/engine-data', arbitragePipelineController.engineData);
router.get('/pipeline/commissions', arbitragePipelineController.commissions);
router.patch('/pipeline/commissions/:houseId', arbitragePipelineController.setCommission);
router.post('/pipeline/commissions/import', arbitragePipelineController.importCommissions);
router.get('/pipeline/commissions/export', arbitragePipelineController.exportCommissions);
router.get('/pipeline/robot', arbitragePipelineController.robotStatus);
router.get('/pipeline/audit/panel', arbitragePipelineController.auditPanel);
router.get('/pipeline/audit/events/:eventId', arbitragePipelineController.auditEvent);
router.get('/pipeline/audit/export', arbitragePipelineController.auditExport);
router.get('/pipeline/coverage/audit', arbitragePipelineController.coverageAudit);
router.get('/pipeline/logs/panel', arbitragePipelineController.logsPanel);
router.get('/pipeline/logs/copy-diagnostic', arbitragePipelineController.logsCopyDiagnostic);
router.get('/pipeline/logs/export-diagnostic', arbitragePipelineController.logsExportDiagnostic);
router.get('/arbitrage-engine/status', arbitrageEngineController.status);
router.post('/arbitrage-engine/evaluate', arbitrageEngineController.evaluate);
router.patch('/arbitrage-engine/configuration', arbitrageEngineController.configure);
router.get('/arbitrage-engine/preflight', arbitrageEngineController.preflight);
router.get('/arbitrage-engine/audit', arbitrageEngineController.audit);
router.get('/homologation/status', homologationController.status);
router.post('/homologation/run', homologationController.run);
router.post('/homologation/oddsagora/import', homologationController.importOddsAgora);
router.get('/homologation/export/:format', homologationController.exportReport);
router.post('/source-intelligence/run', sourceIntelligenceController.runSourceIntelligence);
router.get('/source-intelligence/jobs/:jobId', sourceIntelligenceController.jobStatus);
router.get('/source-intelligence/history', sourceIntelligenceController.history);
router.get('/source-intelligence/history/compare', sourceIntelligenceController.compareHistory);

router.get('/live-audit/houses', liveAuditLabController.houses);
router.get('/live-audit/events/search', liveAuditLabController.searchEvents);
router.get('/live-audit/events/coverage', liveAuditLabController.eventCoverage);
router.get('/live-audit/markets', liveAuditLabController.markets);
router.get('/live-audit/market-view', liveAuditLabController.marketView);
router.get('/live-audit/raw', liveAuditLabController.raw);
router.get('/live-audit/arbitrage-audit', liveAuditLabController.arbitrageAudit);
router.get('/live-audit/validation/status', liveAuditLabController.validationStatus);
router.post('/live-audit/validation/homologate', liveAuditLabController.homologate);
router.post('/live-audit/validation/invalidate', liveAuditLabController.invalidateHomologation);
router.get('/live-audit/validation/history', liveAuditLabController.homologationHistory);
router.get('/live-audit/validation/structural-change', liveAuditLabController.detectStructuralChange);
router.post('/live-audit/audits', liveAuditLabController.saveAuditRecord);
router.get('/live-audit/audits/history', liveAuditLabController.auditHistory);
router.post('/live-audit/issues/report', liveAuditLabController.reportIssue);
router.get('/live-audit/issues/history', liveAuditLabController.issueHistory);

router.get('/storage/report', storageController.report);
router.get('/storage/cleanup/preview', storageController.cleanupPreview);
router.post('/storage/cleanup', storageController.smartCleanup);
router.get('/storage/limits', storageController.limits);
router.patch('/storage/limits', storageController.updateLimits);

router.get('/ai-manager/config', aiManagerController.getConfig);
router.post('/ai-manager/save', aiManagerController.saveConfig);
router.post('/ai-manager/active', aiManagerController.setActiveProvider);
router.post('/ai-manager/test', aiManagerController.testProvider);
router.get('/ai-manager/capabilities', aiManagerController.getCapabilities);

router.post('/foundation/compare', foundationController.compare);
router.post('/foundation/patches', foundationController.createPatch);
router.post('/foundation/patches/apply', foundationController.applyPatch);
router.post('/foundation/patches/:id/rollback', foundationController.rollbackPatch);
router.get('/foundation/patches', foundationController.patchHistory);
router.post('/foundation/backups', foundationController.createBackup);
router.get('/foundation/backups', foundationController.backupHistory);
router.post('/foundation/backups/:id/restore', foundationController.restoreBackup);
router.delete('/foundation/backups/:id', foundationController.deleteBackup);
router.post('/foundation/tests/run', foundationController.runTests);
router.post('/foundation/audit/run', foundationController.runAudit);

module.exports = router;
