const fs = require('fs-extra');
const path = require('path');
const { arbitrageDataPipelineService: pipeline } = require('./arbitrageDataPipelineService');
const { arbitrageEngineService, normalizeName, canonicalEvent, canonicalMarket, canonicalRunner } = require('./arbitrageEngineService');
const { discoveryEngineService } = require('./discoveryEngineService');

function duplicateGroups(items, keyOf) { const groups = new Map();for (const item of items) { const key = keyOf(item);if (!key) continue;if (!groups.has(key)) groups.set(key, []);groups.get(key).push(item); }return [...groups.entries()].filter(([, values]) => new Set(values.map((item) => item.id)).size > 1).map(([key, values]) => ({ key, ids: [...new Set(values.map((item) => item.id))] })); }
function activeOdd(record) { return Number(record.prices?.back ?? record.prices?.odd ?? record.prices?.lay); }
function csvCell(value) { const text = typeof value === 'string' ? value : JSON.stringify(value ?? '');return `"${text.replace(/"/g, '""')}"`; }
function parseCsv(text) { const lines = String(text || '').split(/\r?\n/).filter(Boolean);if (!lines.length) return [];const parse = (line) => { const output = [];let value = '';let quoted = false;for (let index = 0;index < line.length;index += 1) { const char = line[index];if (char === '"' && quoted && line[index + 1] === '"') { value += '"';index += 1; } else if (char === '"') quoted = !quoted;else if (char === ',' && !quoted) { output.push(value.trim());value = ''; } else value += char; }output.push(value.trim());return output; };const headers = parse(lines.shift()).map((item) => normalizeName(item).replace(/ /g, '_'));return lines.map((line) => Object.fromEntries(parse(line).map((value, index) => [headers[index] || `field_${index}`, value]))); }
function benchmarkKeys(dataset = {}) { const rows = Array.isArray(dataset) ? dataset : dataset.rows || [];const events = dataset.events || rows.filter((item) => !item.kind || normalizeName(item.kind) === 'event');const markets = dataset.markets || rows.filter((item) => normalizeName(item.kind) === 'market');const opportunities = dataset.opportunities || rows.filter((item) => normalizeName(item.kind) === 'opportunity');const eventKey = (item) => canonicalEvent({ sport: item.sport || 'unknown', competition: item.competition || 'unknown', event: { name: item.event || item.eventName || item.name || item.key || item.id } }).key;const marketKey = (item) => `${eventKey(item)}|${normalizeName(item.market || item.marketName || item.type || item.key)}`;return { events: new Set(events.map(eventKey).filter(Boolean)), markets: new Set(markets.map(marketKey).filter((value) => value !== '|')), opportunities: new Set(opportunities.map(marketKey).filter((value) => value !== '|')) }; }

class HomologationService {
  constructor(options = {}) { this.pipeline = options.pipeline || pipeline;this.arbitrage = options.arbitrage || arbitrageEngineService;this.discovery = options.discovery || discoveryEngineService;this.workspace = path.resolve(options.workspace || path.join(__dirname, '..', '..', 'workspace'));this.root = path.join(this.workspace, 'homologation');this.reportFile = path.join(this.root, 'latest-report.json');this.benchmarkFile = path.join(this.root, 'oddsagora.snapshot.json');this.oddsStateFile = path.join(this.root, 'odds-state.json');this.lastReport = null; }
  async initialize() { await fs.ensureDir(this.root);this.lastReport = await fs.readJson(this.reportFile).catch(() => null);return this.lastReport; }
  async auditData(records, catalog, now) { const oddsState = await fs.readJson(this.oddsStateFile).catch(() => ({}));const invalidOdds = [];const frozenOdds = [];for (const record of records) { const odd = activeOdd(record);if (!Number.isFinite(odd) || odd <= 1) invalidOdds.push({ recordId: record.id, houseId: record.houseId, odd });const signature = JSON.stringify(record.prices || {});const previous = oddsState[record.id];const changedAt = !previous || previous.signature !== signature ? now : previous.changedAt;oddsState[record.id] = { signature, changedAt, seenAt: now };if (previous && previous.signature === signature && now - Date.parse(changedAt) > Math.max(30000, Number(this.arbitrage.config?.maxDataAgeMs || 15000) * 2)) frozenOdds.push({ recordId: record.id, houseId: record.houseId, unchangedSince: changedAt }); }await fs.writeJson(this.oddsStateFile, oddsState, { spaces: 2 });
    const events = records.map((record) => ({ id: record.event?.id, record, key: `${record.houseId}|${canonicalEvent(record).sport}|${canonicalEvent(record).key}` }));const markets = records.map((record) => ({ id: record.market?.id, record, key: `${record.houseId}|${record.event?.id}|${canonicalMarket(record).key}` }));const selections = records.map((record) => { const event = canonicalEvent(record);const market = canonicalMarket(record);return { id: record.runner?.id, record, key: `${record.houseId}|${record.market?.id}|${canonicalRunner(record, event, market)}` }; });
    return { eventDuplicates: duplicateGroups(events, (item) => item.key), marketDuplicates: duplicateGroups(markets, (item) => item.key), selectionDuplicates: duplicateGroups(selections, (item) => item.key), invalidOdds, frozenOdds, orphanEvents: [...new Set(records.filter((record) => !catalog.events?.[record.event?.id]).map((record) => record.event?.id).filter(Boolean))], orphanMarkets: [...new Set(records.filter((record) => !catalog.markets?.[record.market?.id]).map((record) => record.market?.id).filter(Boolean))], orphanSelections: [...new Set(records.filter((record) => !catalog.selections?.[record.runner?.id]).map((record) => record.runner?.id).filter(Boolean))] };
  }
  rejectedAudit(records, now) { const rejected = [];for (const record of records) { const reasons = [];const odd = activeOdd(record);if (!record.houseId) reasons.push('HOUSE_MISSING');if (!record.event?.name) reasons.push('EVENT_MISSING');if (!record.market?.type) reasons.push('MARKET_MISSING');if (!record.runner?.name) reasons.push('SELECTION_MISSING');if (!Number.isFinite(odd) || odd <= 1) reasons.push('INVALID_ODD');if (!record.commission || !Number.isFinite(Number(record.commission.rate))) reasons.push('COMMISSION_MISSING');if (!['active', 'open', 'opened', 'trading', 'available', 'live', 'prelive'].includes(normalizeName(record.status || 'active'))) reasons.push('MARKET_SUSPENDED');const timestamp = Date.parse(record.lastUpdatedAt || record.normalizedAt || record.timestamp);if (!Number.isFinite(timestamp) || now - timestamp > Number(this.arbitrage.config?.maxDataAgeMs || 15000)) reasons.push('STALE_ODD');if (reasons.length) rejected.push({ recordId: record.id, event: record.event?.name, market: record.market?.name, selection: record.runner?.name, reasons }); }return rejected;
  }
  acceptedAudit() { return [...this.arbitrage.opportunities.values()].map((opportunity) => ({ id: opportunity.id, event: opportunity.event, market: opportunity.market, selections: opportunity.legs.map((leg) => leg.selection), houses: opportunity.legs.map((leg) => leg.houseId), odds: opportunity.legs.map((leg) => leg.odd), commissions: opportunity.legs.map((leg) => leg.commissionRate), stakes: opportunity.legs.map((leg) => leg.stake), grossProfit: opportunity.grossProfit ?? opportunity.netProfit, netProfit: opportunity.netProfit, roi: opportunity.arbitragePercent, validationReason: opportunity.validationReason || 'EQUIVALENT_COMPLETE_MARKET_PROFIT_AFTER_COMMISSION' })); }
  async compareOddsAgora(records) { const dataset = await fs.readJson(this.benchmarkFile).catch(() => null);if (!dataset) return { status: 'SEM_SNAPSHOT_ODDSAGORA', source: 'user-import', events: null, markets: null, opportunities: null, matchPercent: null, fallahExclusive: [], oddsAgoraExclusive: [] };const benchmark = benchmarkKeys(dataset);const fallahEvents = new Set(records.map((record) => canonicalEvent(record).key));const fallahMarkets = new Set(records.map((record) => `${canonicalEvent(record).key}|${canonicalMarket(record).key}`));const fallahOpportunities = new Set([...this.arbitrage.opportunities.values()].map((item) => `${item.event.key}|${item.market.type}|${item.market.line ?? ''}|${item.market.period}`));const intersection = [...fallahEvents].filter((key) => benchmark.events.has(key));const union = new Set([...fallahEvents, ...benchmark.events]);return { status: 'COMPARADO', source: dataset.source || 'OddsAgora user snapshot', importedAt: dataset.importedAt, events: { fallah: fallahEvents.size, oddsAgora: benchmark.events.size }, markets: { fallah: fallahMarkets.size, oddsAgora: benchmark.markets.size }, opportunities: { fallah: fallahOpportunities.size, oddsAgora: benchmark.opportunities.size }, matchPercent: union.size ? Number((intersection.length / union.size * 100).toFixed(2)) : 0, fallahExclusive: [...fallahEvents].filter((key) => !benchmark.events.has(key)), oddsAgoraExclusive: [...benchmark.events].filter((key) => !fallahEvents.has(key)) };
  }
  async stressTest(readers) { const active = readers.filter((reader) => reader.active && !reader.blocked);if (!active.length) return { status: 'NAO_EXECUTADO_SEM_READERS_ATIVOS', readers: 0, simultaneous: false, reconnections: 0, failovers: 0, timeouts: 0, recovered: 0, deduplication: 'not-tested' };const before = this.pipeline.engine.snapshot().total;const started = Date.now();const results = await Promise.allSettled(active.map((reader) => this.pipeline.runReader(reader)));const status = await this.pipeline.status();const accepted = results.filter((item) => item.status === 'fulfilled').length;const readersWithEndpointErrors = results.filter((item) => item.status === 'fulfilled' && Number(item.value?.endpointErrors) > 0).length;const failedReaders = results.filter((item) => item.status === 'rejected').length;return { status: accepted === active.length ? 'APROVADO' : 'PARCIAL', readers: active.length, simultaneous: true, durationMs: Date.now() - started, succeeded: accepted, failed: failedReaders, reconnections: status.diagnostics.reconnects, failovers: readersWithEndpointErrors + failedReaders, timeouts: status.readers.filter((reader) => /abort|timeout/i.test(reader.runtime?.lastError || '')).length, recovered: status.readers.filter((reader) => reader.runtime?.status === 'connected' && reader.runtime?.reconnects > 0).length, deduplication: this.pipeline.engine.snapshot().total >= before ? 'validated' : 'inconclusive' };
  }
  async run({ stress = true } = {}) { await this.initialize();const now = Date.now();const [houses, readers] = await Promise.all([this.discovery.listHouses(), this.pipeline.generator.list()]);const stressResult = stress ? await this.stressTest(readers) : { status: 'NAO_SOLICITADO' };if (stress && readers.length) { const prevMinExec = this.arbitrage.config?.minExecutableSize; const prevMinLiq = this.arbitrage.config?.minMarketLiquidity; if (this.arbitrage.config) { this.arbitrage.config.minExecutableSize = 0; this.arbitrage.config.minMarketLiquidity = 0; } await this.arbitrage.evaluate(); if (this.arbitrage.config) { if (prevMinExec !== undefined) this.arbitrage.config.minExecutableSize = prevMinExec; if (prevMinLiq !== undefined) this.arbitrage.config.minMarketLiquidity = prevMinLiq; } }const pipelineStatus = await this.pipeline.status();const snapshot = this.pipeline.engine.snapshot({ limit: 5000 });const records = snapshot.records;const catalog = await fs.readJson(this.pipeline.engine.catalogFile).catch(() => ({ events: {}, markets: {}, selections: {} }));const dataAudit = await this.auditData(records, catalog, now);const readerErrors = pipelineStatus.readers.filter((reader) => reader.runtime?.errors > 0 || ['reconnecting', 'error'].includes(reader.runtime?.status));const readersWithoutUpdate = pipelineStatus.readers.filter((reader) => reader.active && (!reader.runtime?.lastCaptureAt || now - Date.parse(reader.runtime.lastCaptureAt) > Math.max(reader.heartbeatTimeoutMs || 30000, 30000))).map((reader) => reader.id);const housesWithoutResponse = houses.filter((house) => house.active && !pipelineStatus.readers.some((reader) => reader.houseId === house.id && reader.runtime?.heartbeatHealthy)).map((house) => house.id);const componentAudit = { discovery: { status: 'operational', houses: houses.length }, readerGenerator: { status: 'operational', readers: readers.length }, readers: { status: readerErrors.length ? 'degraded' : 'operational', active: pipelineStatus.diagnostics.activeReaders }, normalizer: { status: records.every((record) => record.schema === 'fallah.normalized/v1') ? 'operational' : 'failed' }, engineData: { status: pipelineStatus.initialized ? 'operational' : 'failed', records: snapshot.total, version: snapshot.version }, arbitrageEngine: { status: this.arbitrage.running ? 'operational' : 'failed', opportunities: this.arbitrage.opportunities.size }, robotConnector: { status: pipelineStatus.robot?.bettingEnabled === false && pipelineStatus.robot?.acceptsRawJson === false ? 'operational' : 'failed', channel: this.arbitrage.status().robotChannel } };
    const noRealData = houses.length === 0 || readers.length === 0 || records.length === 0;const failed = Object.values(componentAudit).some((item) => item.status === 'failed');const report = { schema: 'fallah.homologation-report/v1', generatedAt: new Date().toISOString(), status: failed ? 'FALHA' : noRealData ? 'SEM_DADOS_REAIS' : 'HOMOLOGADO', componentAudit, diagnostics: { connectedHouses: houses.filter((house) => house.active && !housesWithoutResponse.includes(house.id)).length, activeReaders: pipelineStatus.diagnostics.activeReaders, readersWithError: readerErrors.length, lastUpdateAt: snapshot.updatedAt || pipelineStatus.diagnostics.lastCaptureAt, events: pipelineStatus.diagnostics.events, markets: pipelineStatus.diagnostics.markets, selections: pipelineStatus.diagnostics.selections, odds: records.length, responseTimeMs: pipelineStatus.diagnostics.averageCycleMs, latencyMs: pipelineStatus.diagnostics.averageLatencyMs, cpuPercent: pipelineStatus.diagnostics.cpuPercent, memory: pipelineStatus.diagnostics.memory, queues: { readerTimers: this.pipeline.runners.size, engineWrite: 'serialized', discoveryJobs: this.discovery.running.size }, pipelineStatus: failed ? 'failed' : 'operational' }, dataAudit: { ...dataAudit, readersWithoutUpdate, housesWithoutResponse }, arbitrageAudit: { accepted: this.acceptedAudit(), rejected: this.rejectedAudit(records, now) }, oddsAgora: await this.compareOddsAgora(records), stress: stressResult };this.lastReport = report;await fs.writeJson(this.reportFile, report, { spaces: 2 });return report;
  }
  async status() { return this.run({ stress: false }); }
  async importOddsAgora(input) { const dataset = typeof input === 'string' ? { rows: parseCsv(input) } : input;if (!dataset || typeof dataset !== 'object') throw new Error('Snapshot OddsAgora inválido.');const normalized = { ...dataset, schema: 'fallah.oddsagora-snapshot/v1', source: 'OddsAgora user snapshot', importedAt: new Date().toISOString() };const keys = benchmarkKeys(normalized);if (!keys.events.size && !keys.markets.size && !keys.opportunities.size) throw new Error('Snapshot OddsAgora sem eventos, mercados ou oportunidades.');await fs.ensureDir(this.root);await fs.writeJson(this.benchmarkFile, normalized, { spaces: 2 });return { importedAt: normalized.importedAt, events: keys.events.size, markets: keys.markets.size, opportunities: keys.opportunities.size };
  }
  csv(report = this.lastReport) { const rows = [['kind', 'status', 'event', 'market', 'selection', 'house', 'odd', 'commission', 'stake', 'netProfit', 'roi', 'reason']];for (const item of report?.arbitrageAudit?.accepted || []) rows.push(['opportunity', 'validated', item.event?.key, item.market?.type, item.selections, item.houses, item.odds, item.commissions, item.stakes, item.netProfit, item.roi, item.validationReason]);for (const item of report?.arbitrageAudit?.rejected || []) rows.push(['record', 'rejected', item.event, item.market, item.selection, '', '', '', '', '', '', item.reasons]);return rows.map((row) => row.map(csvCell).join(',')).join('\r\n'); }
  logFiles() { return [path.join(this.workspace, 'logs', 'pipeline'), this.root].filter((item) => fs.existsSync(item)); }
}

const homologationService = new HomologationService();
module.exports = { HomologationService, homologationService, parseCsv, benchmarkKeys };
