const assert = require('assert');
const fs = require('fs-extra');
const http = require('http');
const os = require('os');
const path = require('path');
const { ArbitrageDataPipelineService } = require('../src/services/arbitrageDataPipelineService');
const { ArbitrageEngineService } = require('../src/services/arbitrageEngineService');
const { HomologationService } = require('../src/services/homologationService');

function payload(house) { const odds = house === 'a' ? [2.2, 3.6, 4.0] : [2.1, 3.7, 4.2];return ['Alpha', 'Draw', 'Beta'].map((selection, index) => ({ id: `${house}-event`, sport: 'Football', league: house === 'a' ? 'Premier League' : 'League Premier', name: house === 'a' ? 'Alpha vs Beta' : 'Beta x Alpha', market: 'Match Odds', selection, odds: odds[index], status: 'active', timestamp: new Date().toISOString() })); }

async function run() {
  const workspace = await fs.mkdtemp(path.join(os.tmpdir(), 'fallah-homologation-'));const server = http.createServer((req, res) => { if (req.url === '/timeout') return;res.setHeader('Content-Type', 'application/json');res.end(JSON.stringify(payload(req.url === '/a' ? 'a' : 'b'))); });await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));const port = server.address().port;const houses = [{ id: 'house-a', name: 'House A', type: 'sportsbook', url: `http://127.0.0.1:${port}/a`, active: true, blocked: false, commission: 0, commissionActive: true, timeoutMs: 1000, updateIntervalMs: 5000 }, { id: 'house-b', name: 'House B', type: 'exchange', url: `http://127.0.0.1:${port}/b`, active: true, blocked: false, commission: 0, commissionActive: true, timeoutMs: 1000, updateIntervalMs: 5000 }];const pipeline = new ArbitrageDataPipelineService({ workspace });const arbitrage = new ArbitrageEngineService({ workspace, pipeline, engine: pipeline.engine });const discovery = { running: new Map(), listHouses: async () => houses };const homologation = new HomologationService({ workspace, pipeline, arbitrage, discovery });
  try {
    await fs.ensureDir(path.join(workspace, 'discovery-engine'));await fs.writeJson(path.join(workspace, 'discovery-engine', 'houses.json'), { schemaVersion: 1, houses }, { spaces: 2 });for (const house of houses) { const directory = path.join(workspace, 'profiles', house.type === 'exchange' ? 'exchange' : 'bets');await fs.ensureDir(directory);await fs.writeJson(path.join(directory, `${house.id}.profile.json`), { profileSchema: 'fallah.discovery.profile/v2', profileVersion: '2.0.0', house: { id: house.id, name: house.name, configuredType: house.type, configuredUrl: house.url }, platform: { type: house.type }, network: { endpoints: [{ url: `http://127.0.0.1:${port}/timeout`, method: 'GET', resourceTypes: ['Fetch'], contentTypes: ['application/json'], requestHeaders: {} }, { url: house.url, method: 'GET', resourceTypes: ['Fetch'], contentTypes: ['application/json'], requestHeaders: {} }] }, dataMap: {} }, { spaces: 2 }); }
    await pipeline.initialize({ start: false });for (const reader of await pipeline.generator.list()) { reader.maxRetries = 0;const file = reader.file;delete reader.file;delete reader.category;await fs.writeJson(file, reader, { spaces: 2 }); }await pipeline.engine.setCommission('house-a', { rate: 0, active: true });await pipeline.engine.setCommission('house-b', { rate: 0, active: true });await arbitrage.initialize();await homologation.importOddsAgora({ events: [{ name: 'Alpha vs Beta' }], markets: [{ event: 'Alpha vs Beta', market: 'Match Odds' }], opportunities: [{ event: 'Alpha vs Beta', market: 'Match Odds' }] });const report = await homologation.run({ stress: true });
    assert.strictEqual(report.status, 'HOMOLOGADO');assert.strictEqual(report.componentAudit.discovery.status, 'operational');assert.strictEqual(report.componentAudit.normalizer.status, 'operational');assert.strictEqual(report.componentAudit.robotConnector.status, 'operational');assert.strictEqual(report.stress.simultaneous, true);assert.strictEqual(report.stress.succeeded, 2);assert.ok(report.stress.failovers >= 2);assert.ok(report.stress.timeouts >= 0);assert.ok(report.diagnostics.events > 0);assert.ok(report.diagnostics.markets > 0);assert.strictEqual(report.arbitrageAudit.accepted.length, 1);assert.ok(report.arbitrageAudit.accepted[0].netProfit > 0);assert.ok(report.arbitrageAudit.accepted[0].grossProfit > 0);assert.strictEqual(report.oddsAgora.matchPercent, 100);assert.ok(homologation.csv(report).includes('validated'));assert.ok(await fs.pathExists(homologation.reportFile));console.log('FALLAH Engine Homologation tests: OK');
  } finally { await arbitrage.shutdown();await pipeline.shutdown();await new Promise((resolve) => server.close(resolve));await fs.remove(workspace); }
}
run().catch((error) => { console.error(error);process.exitCode = 1; });
